datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/ecommercedb
  username: root
  password: Arthur@21
jpa:
  open-in-view: true
  show-sql: true
  hibernate:
    ddl-auto: update